import type { SchemaDef } from '../../src/lib/schema-types';

const JLPT_LEVELS = ['N5', 'N4', 'N3', 'N2', 'N1'];
const HSK_LEVELS = ['HSK 1', 'HSK 2', 'HSK 3', 'HSK 4', 'HSK 5', 'HSK 6', 'HSK 7-9'];

export const SEED_SCHEMAS: SchemaDef[] = [
  // -------------------------------------------------------------- Japanese
  {
    slug: 'japanese-vocabulary',
    name: 'Japanese Vocabulary',
    itemType: 'JapaneseVocabularyItem',
    category: 'LANGUAGE',
    courseSlug: 'japanese',
    description: 'A Japanese word or expression with reading, meaning, and usage context.',
    fields: [
      { name: 'term', label: 'Term', fieldType: 'TEXT', required: true, description: 'The word in Japanese script (kanji/kana as normally written).', exampleValue: '勉強', llmInstructions: 'Use the most common written form.' },
      { name: 'reading', label: 'Reading', fieldType: 'TEXT', required: true, description: 'Kana reading.', exampleValue: 'べんきょう', llmInstructions: 'Hiragana only; katakana for loanwords.' },
      { name: 'meaning', label: 'Meaning', fieldType: 'TEXT', required: true, exampleValue: 'study', llmInstructions: 'Short English gloss, main senses separated by semicolons.' },
      { name: 'partOfSpeech', label: 'Part of Speech', fieldType: 'ENUM', enumOptions: ['noun', 'verb', 'i-adjective', 'na-adjective', 'adverb', 'particle', 'expression', 'counter', 'other'], exampleValue: 'noun' },
      { name: 'jlptLevel', label: 'JLPT Level', fieldType: 'ENUM', enumOptions: JLPT_LEVELS, exampleValue: 'N5' },
      { name: 'pitchAccent', label: 'Pitch Accent', fieldType: 'TEXT', description: 'Pitch accent pattern, e.g. [0], [1].', exampleValue: '[0]' },
      { name: 'exampleSentence', label: 'Example Sentence', fieldType: 'TEXT', exampleValue: '毎日日本語を勉強します。' },
      { name: 'exampleTranslation', label: 'Example Translation', fieldType: 'TEXT', exampleValue: 'I study Japanese every day.' },
      { name: 'audio', label: 'Audio', fieldType: 'AUDIO', description: 'URL or path to pronunciation audio.' },
      { name: 'frequencyRank', label: 'Frequency Rank', fieldType: 'NUMBER', validationRules: { min: 1 } },
      { name: 'notes', label: 'Notes', fieldType: 'MARKDOWN' },
      { name: 'tags', label: 'Tags', fieldType: 'LIST', validationRules: { itemType: 'text' } },
    ],
    config: {
      flashcardRules: [
        { name: 'recognition', front: '{{term}}', back: '{{reading}} — {{meaning}}' },
        { name: 'production', front: '{{meaning}}', back: '{{term}}（{{reading}}）' },
      ],
      srsRules: { algorithm: 'sm2', newPerDay: 20 },
      llmPrompt: 'Generate Japanese vocabulary items appropriate for the requested JLPT level. Prefer high-frequency words.',
    },
  },
  {
    slug: 'japanese-grammar',
    name: 'Japanese Grammar Point',
    itemType: 'JapaneseGrammarPoint',
    category: 'LANGUAGE',
    courseSlug: 'japanese',
    description: 'A grammar pattern with formation rules and example sentences.',
    fields: [
      { name: 'pattern', label: 'Pattern', fieldType: 'TEXT', required: true, exampleValue: '〜てから' },
      { name: 'meaning', label: 'Meaning', fieldType: 'TEXT', required: true, exampleValue: 'after doing ~' },
      { name: 'jlptLevel', label: 'JLPT Level', fieldType: 'ENUM', enumOptions: JLPT_LEVELS, exampleValue: 'N5' },
      { name: 'formation', label: 'Formation', fieldType: 'LONG_TEXT', description: 'How to construct the pattern.', exampleValue: 'Verb（て form）+ から' },
      { name: 'examples', label: 'Examples', fieldType: 'LIST', validationRules: { itemType: 'text' }, llmInstructions: 'Each entry: Japanese sentence + " / " + English translation.' },
      { name: 'register', label: 'Register', fieldType: 'ENUM', enumOptions: ['casual', 'neutral', 'formal', 'written', 'literary'] },
      { name: 'notes', label: 'Notes', fieldType: 'MARKDOWN', description: 'Nuance, contrasts with similar patterns, pitfalls.' },
    ],
    config: {
      flashcardRules: [
        { name: 'recognition', front: '{{pattern}}', back: '{{meaning}}' },
        { name: 'production', front: 'Grammar for: {{meaning}}', back: '{{pattern}} — {{formation}}' },
      ],
      llmPrompt: 'Generate JLPT grammar points with accurate formation rules and two natural example sentences each.',
    },
  },
  {
    slug: 'japanese-kanji',
    name: 'Japanese Kanji',
    itemType: 'JapaneseKanjiItem',
    category: 'LANGUAGE',
    courseSlug: 'japanese',
    description: 'A single kanji with readings, meanings, and example words.',
    fields: [
      { name: 'character', label: 'Character', fieldType: 'TEXT', required: true, validationRules: { minLength: 1, maxLength: 1 }, exampleValue: '強' },
      { name: 'meaning', label: 'Meaning', fieldType: 'TEXT', required: true, exampleValue: 'strong' },
      { name: 'onyomi', label: "On'yomi", fieldType: 'LIST', validationRules: { itemType: 'text' }, exampleValue: ['キョウ', 'ゴウ'] },
      { name: 'kunyomi', label: "Kun'yomi", fieldType: 'LIST', validationRules: { itemType: 'text' }, exampleValue: ['つよ.い', 'し.いる'] },
      { name: 'strokeCount', label: 'Stroke Count', fieldType: 'NUMBER', validationRules: { min: 1, max: 64 } },
      { name: 'jlptLevel', label: 'JLPT Level', fieldType: 'ENUM', enumOptions: JLPT_LEVELS },
      { name: 'kenteiLevel', label: 'Kanji Kentei Level', fieldType: 'ENUM', enumOptions: ['10', '9', '8', '7', '6', '5', '4', '3', 'Pre-2', '2', 'Pre-1', '1'] },
      { name: 'radicals', label: 'Radicals / Components', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'exampleWords', label: 'Example Words', fieldType: 'LIST', validationRules: { itemType: 'text' }, llmInstructions: 'Format: word（reading）meaning' },
      { name: 'mnemonic', label: 'Mnemonic', fieldType: 'LONG_TEXT' },
    ],
    config: {
      flashcardRules: [
        { name: 'recognition', front: '{{character}}', back: '{{meaning}} — on: {{onyomi}} kun: {{kunyomi}}' },
        { name: 'production', front: 'Write the kanji for: {{meaning}}', back: '{{character}}' },
      ],
      llmPrompt: 'Generate kanji entries with verified readings. Do not invent readings.',
    },
  },
  {
    slug: 'japanese-sentence',
    name: 'Japanese Sentence',
    itemType: 'JapaneseSentence',
    category: 'LANGUAGE',
    courseSlug: 'japanese',
    description: 'A full sentence for reading, listening, and sentence-mining practice.',
    fields: [
      { name: 'sentence', label: 'Sentence', fieldType: 'TEXT', required: true, exampleValue: '電車が遅れたので、会議に間に合わなかった。' },
      { name: 'reading', label: 'Reading', fieldType: 'TEXT', description: 'Full kana reading.' },
      { name: 'translation', label: 'Translation', fieldType: 'TEXT', required: true },
      { name: 'difficulty', label: 'Difficulty', fieldType: 'ENUM', enumOptions: JLPT_LEVELS },
      { name: 'grammarPoints', label: 'Grammar Points', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'vocabTerms', label: 'Key Vocabulary', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'source', label: 'Source', fieldType: 'TEXT', description: 'Book, show, article the sentence came from.' },
      { name: 'audio', label: 'Audio', fieldType: 'AUDIO' },
    ],
    config: {
      flashcardRules: [{ name: 'comprehension', front: '{{sentence}}', back: '{{translation}}' }],
      llmPrompt: 'Generate natural Japanese sentences at the requested level, each using one target grammar point.',
    },
  },
  {
    slug: 'japanese-pitch-accent',
    name: 'Japanese Pitch Accent Item',
    itemType: 'JapanesePitchAccentItem',
    category: 'LANGUAGE',
    courseSlug: 'japanese',
    description: 'Pitch accent drill item for minimal pairs and common words.',
    fields: [
      { name: 'term', label: 'Term', fieldType: 'TEXT', required: true, exampleValue: '雨' },
      { name: 'reading', label: 'Reading', fieldType: 'TEXT', required: true, exampleValue: 'あめ' },
      { name: 'accentPattern', label: 'Accent Pattern', fieldType: 'TEXT', required: true, description: 'Downstep index notation, e.g. [1].', exampleValue: '[1]' },
      { name: 'minimalPair', label: 'Minimal Pair', fieldType: 'TEXT', description: 'Contrasting word, e.g. 飴 [0].' },
      { name: 'audio', label: 'Audio', fieldType: 'AUDIO' },
    ],
    config: {
      flashcardRules: [{ name: 'recall', front: 'Pitch accent of {{term}}（{{reading}}）?', back: '{{accentPattern}}' }],
    },
  },
  // --------------------------------------------------------------- Chinese
  {
    slug: 'chinese-vocabulary',
    name: 'Chinese Vocabulary',
    itemType: 'ChineseVocabularyItem',
    category: 'LANGUAGE',
    courseSlug: 'chinese',
    description: 'A Chinese word with simplified/traditional forms, pinyin, and meaning.',
    fields: [
      { name: 'simplified', label: 'Simplified', fieldType: 'TEXT', required: true, exampleValue: '学习' },
      { name: 'traditional', label: 'Traditional', fieldType: 'TEXT', exampleValue: '學習', llmInstructions: 'Omit if identical to simplified.' },
      { name: 'pinyin', label: 'Pinyin', fieldType: 'TEXT', required: true, exampleValue: 'xuéxí', llmInstructions: 'Tone marks, not tone numbers.' },
      { name: 'meaning', label: 'Meaning', fieldType: 'TEXT', required: true, exampleValue: 'to study; to learn' },
      { name: 'hskLevel', label: 'HSK Level', fieldType: 'ENUM', enumOptions: HSK_LEVELS, exampleValue: 'HSK 1' },
      { name: 'partOfSpeech', label: 'Part of Speech', fieldType: 'ENUM', enumOptions: ['noun', 'verb', 'adjective', 'adverb', 'measure word', 'conjunction', 'particle', 'expression', 'other'] },
      { name: 'exampleSentence', label: 'Example Sentence', fieldType: 'TEXT', exampleValue: '我每天学习中文。' },
      { name: 'exampleTranslation', label: 'Example Translation', fieldType: 'TEXT' },
      { name: 'audio', label: 'Audio', fieldType: 'AUDIO' },
      { name: 'frequencyRank', label: 'Frequency Rank', fieldType: 'NUMBER', validationRules: { min: 1 } },
      { name: 'notes', label: 'Notes', fieldType: 'MARKDOWN' },
    ],
    config: {
      flashcardRules: [
        { name: 'recognition', front: '{{simplified}}', back: '{{pinyin}} — {{meaning}}' },
        { name: 'production', front: '{{meaning}}', back: '{{simplified}} ({{pinyin}})' },
      ],
      srsRules: { algorithm: 'sm2', newPerDay: 20 },
      llmPrompt: 'Generate Chinese vocabulary for the requested HSK level with accurate pinyin tone marks.',
    },
  },
  {
    slug: 'chinese-character',
    name: 'Chinese Character',
    itemType: 'ChineseCharacterItem',
    category: 'LANGUAGE',
    courseSlug: 'chinese',
    description: 'A single hanzi with components, readings, and example words.',
    fields: [
      { name: 'simplified', label: 'Simplified', fieldType: 'TEXT', required: true, validationRules: { minLength: 1, maxLength: 1 }, exampleValue: '学' },
      { name: 'traditional', label: 'Traditional', fieldType: 'TEXT', exampleValue: '學' },
      { name: 'pinyin', label: 'Pinyin', fieldType: 'TEXT', required: true, exampleValue: 'xué' },
      { name: 'meaning', label: 'Meaning', fieldType: 'TEXT', required: true, exampleValue: 'to study; school' },
      { name: 'strokeCount', label: 'Stroke Count', fieldType: 'NUMBER', validationRules: { min: 1, max: 64 } },
      { name: 'radical', label: 'Radical', fieldType: 'TEXT', exampleValue: '子' },
      { name: 'components', label: 'Components', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'hskLevel', label: 'HSK Level', fieldType: 'ENUM', enumOptions: HSK_LEVELS },
      { name: 'exampleWords', label: 'Example Words', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'mnemonic', label: 'Mnemonic', fieldType: 'LONG_TEXT' },
    ],
    config: {
      flashcardRules: [
        { name: 'recognition', front: '{{simplified}}', back: '{{pinyin}} — {{meaning}}' },
        { name: 'production', front: 'Write the character for: {{meaning}}', back: '{{simplified}}' },
      ],
    },
  },
  {
    slug: 'chinese-sentence',
    name: 'Chinese Sentence',
    itemType: 'ChineseSentence',
    category: 'LANGUAGE',
    courseSlug: 'chinese',
    description: 'A full sentence for reading, listening, and pattern practice.',
    fields: [
      { name: 'simplified', label: 'Sentence (Simplified)', fieldType: 'TEXT', required: true },
      { name: 'traditional', label: 'Sentence (Traditional)', fieldType: 'TEXT' },
      { name: 'pinyin', label: 'Pinyin', fieldType: 'TEXT' },
      { name: 'translation', label: 'Translation', fieldType: 'TEXT', required: true },
      { name: 'hskLevel', label: 'HSK Level', fieldType: 'ENUM', enumOptions: HSK_LEVELS },
      { name: 'grammarPoints', label: 'Grammar Points', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'audio', label: 'Audio', fieldType: 'AUDIO' },
    ],
    config: {
      flashcardRules: [{ name: 'comprehension', front: '{{simplified}}', back: '{{pinyin}} — {{translation}}' }],
    },
  },
  {
    slug: 'chinese-grammar',
    name: 'Chinese Grammar Point',
    itemType: 'ChineseGrammarPoint',
    category: 'LANGUAGE',
    courseSlug: 'chinese',
    description: 'A grammar pattern with structure and example sentences.',
    fields: [
      { name: 'pattern', label: 'Pattern', fieldType: 'TEXT', required: true, exampleValue: '是……的' },
      { name: 'meaning', label: 'Meaning', fieldType: 'TEXT', required: true, exampleValue: 'emphasizes time/place/manner of a past event' },
      { name: 'hskLevel', label: 'HSK Level', fieldType: 'ENUM', enumOptions: HSK_LEVELS },
      { name: 'structure', label: 'Structure', fieldType: 'LONG_TEXT', exampleValue: 'Subject + 是 + [emphasized info] + Verb + 的' },
      { name: 'examples', label: 'Examples', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'notes', label: 'Notes', fieldType: 'MARKDOWN' },
    ],
    config: {
      flashcardRules: [{ name: 'recognition', front: '{{pattern}}', back: '{{meaning}} — {{structure}}' }],
    },
  },
  {
    slug: 'chinese-tone-drill',
    name: 'Chinese Tone Drill',
    itemType: 'ChineseToneDrill',
    category: 'LANGUAGE',
    courseSlug: 'chinese',
    description: 'Tone discrimination and production drill items.',
    fields: [
      { name: 'syllables', label: 'Syllables', fieldType: 'TEXT', required: true, description: 'The drilled syllable(s) with tone marks.', exampleValue: 'mā má mǎ mà' },
      { name: 'hanzi', label: 'Hanzi', fieldType: 'TEXT', exampleValue: '妈 麻 马 骂' },
      { name: 'tonePattern', label: 'Tone Pattern', fieldType: 'TEXT', required: true, exampleValue: '1-2-3-4' },
      { name: 'audio', label: 'Audio', fieldType: 'AUDIO' },
      { name: 'notes', label: 'Notes', fieldType: 'TEXT' },
    ],
    config: {
      flashcardRules: [{ name: 'toneRecall', front: 'Tones of {{hanzi}}?', back: '{{syllables}} ({{tonePattern}})' }],
    },
  },
  // ------------------------------------------------------------------ Math
  {
    slug: 'math-definition',
    name: 'Math Definition',
    itemType: 'MathDefinition',
    category: 'MATH',
    courseSlug: 'math',
    description: 'A mathematical definition with intuition and examples.',
    fields: [
      { name: 'name', label: 'Name', fieldType: 'TEXT', required: true, exampleValue: 'Group' },
      { name: 'statement', label: 'Statement', fieldType: 'LATEX', required: true, exampleValue: 'A set $G$ with a binary operation $\\cdot$ satisfying closure, associativity, identity, and inverses.' },
      { name: 'field', label: 'Field', fieldType: 'TEXT', description: 'Area of math, e.g. "Abstract Algebra".', exampleValue: 'Abstract Algebra' },
      { name: 'intuition', label: 'Intuition', fieldType: 'MARKDOWN', llmInstructions: 'One or two sentences of plain-language intuition.' },
      { name: 'examples', label: 'Examples', fieldType: 'LIST', validationRules: { itemType: 'text' }, exampleValue: ['(Z, +)', 'S_n under composition'] },
      { name: 'nonExamples', label: 'Non-examples', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'relatedTheorems', label: 'Related Theorems', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'source', label: 'Source', fieldType: 'TEXT', description: 'Textbook and section.' },
    ],
    config: {
      flashcardRules: [
        { name: 'recall', front: 'Define: {{name}}', back: '{{statement}}' },
        { name: 'recognition', front: '{{statement}}', back: '{{name}}' },
      ],
      llmPrompt: 'Generate precise definitions using standard LaTeX. Statements must be mathematically correct.',
    },
  },
  {
    slug: 'math-theorem',
    name: 'Math Theorem',
    itemType: 'MathTheorem',
    category: 'MATH',
    courseSlug: 'math',
    description: 'A theorem with statement, hypotheses, and proof sketch.',
    fields: [
      { name: 'name', label: 'Name', fieldType: 'TEXT', required: true, exampleValue: "Lagrange's Theorem" },
      { name: 'statement', label: 'Statement', fieldType: 'LATEX', required: true, exampleValue: 'If $H \\le G$ and $G$ is finite, then $|H|$ divides $|G|$.' },
      { name: 'hypotheses', label: 'Hypotheses', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'proofSketch', label: 'Proof Sketch', fieldType: 'MARKDOWN', llmInstructions: 'Key idea in 2–4 sentences; not the full proof.' },
      { name: 'field', label: 'Field', fieldType: 'TEXT', exampleValue: 'Group Theory' },
      { name: 'importance', label: 'Importance', fieldType: 'ENUM', enumOptions: ['core', 'important', 'useful', 'niche'] },
      { name: 'relatedDefinitions', label: 'Related Definitions', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'source', label: 'Source', fieldType: 'TEXT' },
    ],
    config: {
      flashcardRules: [
        { name: 'recall', front: 'State: {{name}}', back: '{{statement}}' },
        { name: 'proofIdea', front: 'Proof idea of {{name}}?', back: '{{proofSketch}}' },
      ],
    },
  },
  {
    slug: 'math-exercise',
    name: 'Math Exercise',
    itemType: 'MathExercise',
    category: 'MATH',
    courseSlug: 'math',
    description: 'A practice problem with solution and hints.',
    fields: [
      { name: 'problem', label: 'Problem', fieldType: 'LATEX', required: true },
      { name: 'solution', label: 'Solution', fieldType: 'LATEX' },
      { name: 'hints', label: 'Hints', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'difficulty', label: 'Difficulty', fieldType: 'ENUM', enumOptions: ['routine', 'standard', 'challenging', 'competition', 'research-adjacent'] },
      { name: 'field', label: 'Field', fieldType: 'TEXT' },
      { name: 'topics', label: 'Topics', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'source', label: 'Source', fieldType: 'TEXT' },
    ],
    config: {
      practiceRules: [{ type: 'PROBLEM_SOLVING', promptField: 'problem', answerField: 'solution' }],
      llmPrompt: 'Generate exercises with fully worked, correct solutions. Verify each solution before including it.',
    },
  },
  {
    slug: 'math-proof',
    name: 'Math Proof',
    itemType: 'MathProof',
    category: 'MATH',
    courseSlug: 'math',
    description: 'A full proof for reconstruction practice.',
    fields: [
      { name: 'theoremName', label: 'Theorem Name', fieldType: 'TEXT', required: true },
      { name: 'statement', label: 'Statement', fieldType: 'LATEX', required: true },
      { name: 'proof', label: 'Proof', fieldType: 'MARKDOWN', required: true, llmInstructions: 'Complete rigorous proof with LaTeX for formulas.' },
      { name: 'technique', label: 'Technique', fieldType: 'ENUM', enumOptions: ['direct', 'contradiction', 'contrapositive', 'induction', 'construction', 'diagonalization', 'other'] },
      { name: 'keySteps', label: 'Key Steps', fieldType: 'LIST', validationRules: { itemType: 'text' }, description: 'Ordered outline used for proof reconstruction practice.' },
      { name: 'field', label: 'Field', fieldType: 'TEXT' },
    ],
    config: {
      practiceRules: [{ type: 'PROOF_RECONSTRUCTION', promptField: 'statement', answerField: 'proof' }],
    },
  },
  // --------------------------------------------------------- Random Skills
  {
    slug: 'typing-drill',
    name: 'Typing Drill',
    itemType: 'TypingDrill',
    category: 'SKILL',
    courseSlug: 'typing',
    description: 'A typing practice drill targeting speed, accuracy, or weak keys.',
    fields: [
      { name: 'name', label: 'Name', fieldType: 'TEXT', required: true, exampleValue: 'Home row burst' },
      { name: 'text', label: 'Drill Text', fieldType: 'LONG_TEXT', required: true },
      { name: 'category', label: 'Category', fieldType: 'ENUM', enumOptions: ['home-row', 'top-row', 'bottom-row', 'numbers', 'symbols', 'code', 'prose', 'weak-keys'] },
      { name: 'focusKeys', label: 'Focus Keys', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'targetWpm', label: 'Target WPM', fieldType: 'NUMBER', validationRules: { min: 1, max: 300 } },
      { name: 'targetAccuracy', label: 'Target Accuracy %', fieldType: 'NUMBER', validationRules: { min: 0, max: 100 }, defaultValue: 97 },
    ],
    config: {
      practiceRules: [{ type: 'TYPING_DRILL', promptField: 'name', answerField: 'text' }],
    },
  },
  {
    slug: 'nato-alphabet',
    name: 'NATO Alphabet Item',
    itemType: 'NATOAlphabetItem',
    category: 'SKILL',
    courseSlug: 'nato-alphabet',
    description: 'One letter of the NATO phonetic alphabet.',
    fields: [
      { name: 'letter', label: 'Letter', fieldType: 'TEXT', required: true, validationRules: { minLength: 1, maxLength: 1, pattern: '^[A-Z]$' }, exampleValue: 'A' },
      { name: 'word', label: 'Code Word', fieldType: 'TEXT', required: true, exampleValue: 'Alfa' },
      { name: 'pronunciation', label: 'Pronunciation', fieldType: 'TEXT', exampleValue: 'AL-fah' },
      { name: 'mnemonic', label: 'Mnemonic', fieldType: 'TEXT' },
    ],
    config: {
      flashcardRules: [
        { name: 'letterToWord', front: '{{letter}} → ?', back: '{{word}}' },
        { name: 'wordToLetter', front: '{{word}} → ?', back: '{{letter}}' },
      ],
    },
  },
  {
    slug: 'geoguessr-clue',
    name: 'GeoGuessr Clue',
    itemType: 'GeoGuessrClue',
    category: 'SKILL',
    courseSlug: 'geoguessr',
    description: 'A country-identification clue: signs, plates, bollards, driving side, language, scenery.',
    fields: [
      { name: 'country', label: 'Country', fieldType: 'TEXT', required: true, exampleValue: 'Norway' },
      { name: 'clueType', label: 'Clue Type', fieldType: 'ENUM', required: true, enumOptions: ['flag', 'road-sign', 'license-plate', 'bollard', 'driving-side', 'language-script', 'utility-pole', 'road-marking', 'scenery', 'map-region', 'other'], exampleValue: 'bollard' },
      { name: 'description', label: 'Description', fieldType: 'LONG_TEXT', required: true, exampleValue: 'White bollard, black band near top, rounded rectangular reflector.' },
      { name: 'image', label: 'Image', fieldType: 'IMAGE' },
      { name: 'region', label: 'Region', fieldType: 'TEXT', description: 'Sub-national region if the clue is region-specific.' },
      { name: 'reliability', label: 'Reliability', fieldType: 'ENUM', enumOptions: ['high', 'medium', 'low'], defaultValue: 'medium' },
      { name: 'notes', label: 'Notes', fieldType: 'MARKDOWN' },
    ],
    config: {
      flashcardRules: [
        { name: 'clueToCountry', front: '{{clueType}}: {{description}}', back: '{{country}}' },
        { name: 'countryToClue', front: 'Distinctive {{clueType}} of {{country}}?', back: '{{description}}' },
      ],
    },
  },
  // ----------------------------------------------------------------- Books
  {
    slug: 'book',
    name: 'Book',
    itemType: 'Book',
    category: 'BOOK',
    courseSlug: 'books',
    description: 'A book record for import into the reading tracker.',
    fields: [
      { name: 'title', label: 'Title', fieldType: 'TEXT', required: true },
      { name: 'author', label: 'Author', fieldType: 'TEXT' },
      { name: 'category', label: 'Category', fieldType: 'TEXT', exampleValue: 'History' },
      { name: 'status', label: 'Status', fieldType: 'ENUM', enumOptions: ['want_to_read', 'reading', 'finished', 'paused', 'abandoned'], defaultValue: 'want_to_read' },
      { name: 'language', label: 'Language', fieldType: 'TEXT' },
      { name: 'rating', label: 'Rating', fieldType: 'NUMBER', validationRules: { min: 1, max: 5 } },
      { name: 'pageCount', label: 'Page Count', fieldType: 'NUMBER', validationRules: { min: 1 }, exampleValue: 320 },
      { name: 'tags', label: 'Tags', fieldType: 'LIST', validationRules: { itemType: 'text' } },
      { name: 'summary', label: 'Summary', fieldType: 'MARKDOWN' },
    ],
  },
  {
    slug: 'book-note',
    name: 'Book Note',
    itemType: 'BookNote',
    category: 'BOOK',
    courseSlug: 'books',
    description: 'A note, idea, argument, character, definition, or reflection from a book.',
    fields: [
      { name: 'bookTitle', label: 'Book Title', fieldType: 'TEXT', required: true, importInstructions: 'Must match an existing book title exactly.' },
      { name: 'kind', label: 'Kind', fieldType: 'ENUM', required: true, enumOptions: ['note', 'idea', 'argument', 'character', 'definition', 'formula', 'passage', 'reflection'], defaultValue: 'note' },
      { name: 'content', label: 'Content', fieldType: 'LONG_TEXT', required: true },
      { name: 'location', label: 'Location', fieldType: 'TEXT', description: 'Chapter, page, or Kindle location.' },
      { name: 'remember', label: 'Remember This', fieldType: 'BOOLEAN', defaultValue: false, description: 'Marks the note for flashcard generation.' },
    ],
  },
  {
    slug: 'book-quote',
    name: 'Book Quote',
    itemType: 'BookQuote',
    category: 'BOOK',
    courseSlug: 'books',
    description: 'A verbatim quote worth keeping.',
    fields: [
      { name: 'bookTitle', label: 'Book Title', fieldType: 'TEXT', required: true },
      { name: 'quote', label: 'Quote', fieldType: 'LONG_TEXT', required: true },
      { name: 'location', label: 'Location', fieldType: 'TEXT' },
      { name: 'whyItMatters', label: 'Why It Matters', fieldType: 'MARKDOWN' },
    ],
  },
  {
    slug: 'book-summary',
    name: 'Book Summary',
    itemType: 'BookSummary',
    category: 'BOOK',
    courseSlug: 'books',
    description: 'A chapter or whole-book summary with key ideas.',
    fields: [
      { name: 'bookTitle', label: 'Book Title', fieldType: 'TEXT', required: true },
      { name: 'scope', label: 'Scope', fieldType: 'TEXT', description: '"whole book" or a chapter reference.', defaultValue: 'whole book' },
      { name: 'summary', label: 'Summary', fieldType: 'MARKDOWN', required: true },
      { name: 'keyIdeas', label: 'Key Ideas', fieldType: 'LIST', validationRules: { itemType: 'text' } },
    ],
  },
  {
    slug: 'book-flashcard',
    name: 'Book Flashcard',
    itemType: 'BookFlashcard',
    category: 'BOOK',
    courseSlug: 'books',
    description: 'A ready-made flashcard derived from book content.',
    fields: [
      { name: 'bookTitle', label: 'Book Title', fieldType: 'TEXT', required: true },
      { name: 'front', label: 'Front', fieldType: 'TEXT', required: true },
      { name: 'back', label: 'Back', fieldType: 'LONG_TEXT', required: true },
      { name: 'context', label: 'Context', fieldType: 'TEXT', description: 'Where in the book this comes from.' },
    ],
    config: {
      flashcardRules: [{ name: 'direct', front: '{{front}}', back: '{{back}}' }],
    },
  },
];
